#!/usr/bin/env bash
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
function Purpose() {
# begin block comment =============================
: <<'END'

#  Purpose:  convert xls to csv for eam asset list  2016-10-14_Fri_16.05-PM



albe@pmdsdata3:/home/file/import1$ gem install roo
ERROR:  Could not find a valid gem 'roo' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/specs.4.8.gz)

_____________
          
          
http://help.rubygems.org/kb/rubygems/installing-gems-with-no-network
          
gem install roo -i localgems1 --no-rdoc --no-ri

copy the gem files....
  copy localgems1/cache to other machine

cd /path/to/USB_drive/gems
cd /home/albe/tmp01/localgems/cache
gem install --force --local *.gem



END
# end block comment ===============================
}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#cd ; 
date ; set +vx  ; set -vx ; # echo off, then echo on
#

# Main: put code here...

ruby /home/albe/bin/xl2csv.rb /home/file/import1/eam-asset-1014.xlsx | ruby /home/albe/bin/eamaddcol.rb > /home/file/import1/eam.csv

#
date
#
